language: ruby
before_install:
  - gem update bundler

rvm:
  - 2.1.2

#script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - hola@gessgallardo.com
    on_failure: change
    on_success: never